export enum EspecialidadConsultorio {
    CLINICA = 'CLINICA',
    PEDIATRIA = 'PEDIATRIA',
    CARDIOLOGIA = 'CARDIOLOGIA',
    GINECOLOGIA = 'GINECOLOGIA',
    DERMATOLOGIA = 'DERMATOLOGIA',
    TRAUMATOLOGIA = 'TRAUMATOLOGIA',
    NEUROLOGIA = 'NEUROLOGIA',
}
